info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-08-17T06:33:49.002Z"}
error: Could not connect to the database. connect ECONNREFUSED 127.0.0.1:3306 {"name":"SequelizeConnectionRefusedError","original":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-4078,"port":3306,"syscall":"connect"},"parent":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-4078,"port":3306,"syscall":"connect"},"stack":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306\n    at Client._connectionCallback (C:\\Users\\admin\\Desktop\\fundoo_Notes\\newBookStore\\BookStore\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:184:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\admin\\Desktop\\fundoo_Notes\\newBookStore\\BookStore\\node_modules\\pg\\lib\\client.js:327:19)\n    at Client._handleErrorEvent (C:\\Users\\admin\\Desktop\\fundoo_Notes\\newBookStore\\BookStore\\node_modules\\pg\\lib\\client.js:337:19)\n    at Connection.emit (node:events:519:28)\n    at Socket.reportStreamError (C:\\Users\\admin\\Desktop\\fundoo_Notes\\newBookStore\\BookStore\\node_modules\\pg\\lib\\connection.js:58:12)\n    at Socket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2024-08-17T06:33:49.043Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2024-08-17T06:35:21.371Z"}
info: Connected to the database. {"timestamp":"2024-08-17T06:35:21.687Z"}
